# Generated by Django 4.1.7 on 2023-04-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='aAppr_def',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='aBC',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='aS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='chant',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='code_pilotage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='cree_le_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='cree_par',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='ctrPr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='dFI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='dPr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='delai_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='delai_sec_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='designation_article',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='di',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='div',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='dv',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='elément_de_OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gAc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gML',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gcha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gest',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='grPl',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='grpA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='grpe_march',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='hierarch_produits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='horiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='iC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='int_ajust_amont',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='int_ajust_aval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='langue',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='lot_fixe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mag',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mgApp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mode_de_comparaison_des_besoin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='nAl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='pas_de_CCR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='poids_brut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='poids_net',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='prPiAt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='profil',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='rebut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='stock_maximum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='stock_securite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='tCy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='tL',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='tRe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='taille_de_lot_du_CCR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='taille_l_min',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='taille_lot_mx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='texte_article',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='tyAr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='tyP',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='typ_app',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_1',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_5',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_6',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='uQ_7',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='unP',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='unP_1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='val_arrondie',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
