# Generated by Django 4.1.7 on 2023-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='imported_by',
            field=models.CharField(default='Rhimi  Thouraya', max_length=50),
        ),
    ]
