# Generated by Django 4.1.7 on 2023-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mara_marc_for_ms_aappr_def_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='r',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
