# Generated by Django 4.1.7 on 2023-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('imported_by', models.CharField(default=' Rhimi Thouraya', max_length=50)),
                ('updated_by', models.CharField(default=' Rhimi Thouraya', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(max_length=30, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('restored_at', models.DateTimeField(auto_now=True, null=True)),
                ('restored_by', models.CharField(default='Thouraya Rhimi  ', max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
