# Generated by Django 4.1.7 on 2023-08-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_equipems_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipems',
            name='date',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='restored_by',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equipems',
            name='updated_by',
        ),
    ]
