# Generated by Django 4.1.7 on 2023-04-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mara_marc_for_ms_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='r',
            field=models.TextField(blank=True, null=True),
        ),
    ]
