# Generated by Django 4.1.7 on 2023-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mara_marc_for_ms_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='aAppr_def',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='iC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mgApp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='nAl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
