# Generated by Django 4.1.7 on 2023-04-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_mara_marc_for_ms_aappr_def_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='gS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='int_ajust_amont',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='int_ajust_aval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='mode_de_comparaison_des_besoin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
