# Generated by Django 4.1.7 on 2023-09-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuserpermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rute',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='restored_by',
        ),
    ]
