# Generated by Django 4.1.7 on 2023-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_mara_marc_for_ms_code_pilotage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='pas_de_CCR',
            field=models.TextField(blank=True, null=True),
        ),
    ]
