# Generated by Django 4.1.7 on 2023-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_file_updated_file_imported_at_file_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='imported_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='imported_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
