# Generated by Django 4.1.7 on 2023-04-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_mara_marc_for_ms_pas_de_ccr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mara_marc_for_ms',
            name='aS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
