# Generated by Django 4.1.7 on 2023-09-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_condition_imported_at_condition_imported_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='imported_at',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='updated_by',
        ),
    ]
