# Generated by Django 4.1.7 on 2023-09-08 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_condition_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='imported_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=50),
        ),
        migrations.AddField(
            model_name='condition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='updated_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=30),
        ),
        migrations.AddField(
            model_name='file',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=30),
        ),
        migrations.AddField(
            model_name='resulta',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulta',
            name='imported_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=50),
        ),
        migrations.AddField(
            model_name='resulta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resulta',
            name='updated_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=30),
        ),
    ]
