# Generated by Django 4.1.7 on 2023-09-09 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_condition_imported_at_condition_imported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='imported_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_by',
            field=models.CharField(default=' Rhimi Thouraya', max_length=30),
        ),
    ]
